/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RKHReport {
  'id' : bigint,
  'hasilKegiatan' : string,
  'kegiatan' : string,
  'tanggal' : string,
  'createdAt' : bigint,
  'user' : Principal,
  'lokasi' : string,
  'keterangan' : [] | [string],
  'jumlahSasaran' : bigint,
  'sasaran' : string,
}
export interface UserProfile {
  'nip' : string,
  'nama' : string,
  'wilayahKerja' : string,
  'nomorHp' : string,
  'jabatan' : string,
  'tandaTangan' : [] | [string],
  'unitKerja' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReport' : ActorMethod<[RKHReport], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRKHReport' : ActorMethod<
    [
      {
        'hasilKegiatan' : string,
        'kegiatan' : string,
        'tanggal' : string,
        'lokasi' : string,
        'keterangan' : [] | [string],
        'jumlahSasaran' : bigint,
        'sasaran' : string,
      },
    ],
    RKHReport
  >,
  'filterReportsByUser' : ActorMethod<[Principal], Array<RKHReport>>,
  'filterReportsByUserAndMonth' : ActorMethod<
    [Principal, string],
    Array<RKHReport>
  >,
  'filterReportsByUserAndMonthYear' : ActorMethod<
    [Principal, string, string],
    Array<RKHReport>
  >,
  'filterReportsByUserAndYear' : ActorMethod<
    [Principal, string],
    Array<RKHReport>
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReportById' : ActorMethod<[bigint], RKHReport>,
  'getReports' : ActorMethod<[], Array<RKHReport>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isValidNumaiIndicator' : ActorMethod<[Array<bigint>], boolean>,
  'queryReports' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [Principal]],
    Array<RKHReport>
  >,
  'queryReportsYearly' : ActorMethod<[string], Array<RKHReport>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'updateReport' : ActorMethod<[Array<RKHReport>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];