/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RKHReport = IDL.Record({
  'id' : IDL.Nat,
  'hasilKegiatan' : IDL.Text,
  'kegiatan' : IDL.Text,
  'tanggal' : IDL.Text,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'lokasi' : IDL.Text,
  'keterangan' : IDL.Opt(IDL.Text),
  'jumlahSasaran' : IDL.Nat,
  'sasaran' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'nip' : IDL.Text,
  'nama' : IDL.Text,
  'wilayahKerja' : IDL.Text,
  'nomorHp' : IDL.Text,
  'jabatan' : IDL.Text,
  'unitKerja' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRKHReport' : IDL.Func(
      [
        IDL.Record({
          'hasilKegiatan' : IDL.Text,
          'kegiatan' : IDL.Text,
          'tanggal' : IDL.Text,
          'lokasi' : IDL.Text,
          'keterangan' : IDL.Opt(IDL.Text),
          'jumlahSasaran' : IDL.Nat,
          'sasaran' : IDL.Text,
        }),
      ],
      [RKHReport],
      [],
    ),
  'deleteReport' : IDL.Func([IDL.Nat], [], []),
  'filterReports' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(RKHReport)],
      ['query'],
    ),
  'getAllReports' : IDL.Func([], [IDL.Vec(RKHReport)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyReports' : IDL.Func([], [IDL.Vec(RKHReport)], ['query']),
  'getReportById' : IDL.Func([IDL.Nat], [RKHReport], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'queryRKHReports' : IDL.Func(
      [
        IDL.Record({
          'tahun' : IDL.Opt(IDL.Text),
          'tanggal' : IDL.Opt(IDL.Text),
          'user' : IDL.Opt(IDL.Principal),
          'bulan' : IDL.Opt(IDL.Text),
        }),
      ],
      [IDL.Vec(RKHReport)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'updateMyProfile' : IDL.Func([UserProfile], [], []),
  'updateReport' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'hasilKegiatan' : IDL.Text,
          'kegiatan' : IDL.Text,
          'tanggal' : IDL.Text,
          'lokasi' : IDL.Text,
          'keterangan' : IDL.Opt(IDL.Text),
          'jumlahSasaran' : IDL.Nat,
          'sasaran' : IDL.Text,
        }),
      ],
      [RKHReport],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RKHReport = IDL.Record({
    'id' : IDL.Nat,
    'hasilKegiatan' : IDL.Text,
    'kegiatan' : IDL.Text,
    'tanggal' : IDL.Text,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'lokasi' : IDL.Text,
    'keterangan' : IDL.Opt(IDL.Text),
    'jumlahSasaran' : IDL.Nat,
    'sasaran' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'nip' : IDL.Text,
    'nama' : IDL.Text,
    'wilayahKerja' : IDL.Text,
    'nomorHp' : IDL.Text,
    'jabatan' : IDL.Text,
    'unitKerja' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRKHReport' : IDL.Func(
        [
          IDL.Record({
            'hasilKegiatan' : IDL.Text,
            'kegiatan' : IDL.Text,
            'tanggal' : IDL.Text,
            'lokasi' : IDL.Text,
            'keterangan' : IDL.Opt(IDL.Text),
            'jumlahSasaran' : IDL.Nat,
            'sasaran' : IDL.Text,
          }),
        ],
        [RKHReport],
        [],
      ),
    'deleteReport' : IDL.Func([IDL.Nat], [], []),
    'filterReports' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(RKHReport)],
        ['query'],
      ),
    'getAllReports' : IDL.Func([], [IDL.Vec(RKHReport)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyReports' : IDL.Func([], [IDL.Vec(RKHReport)], ['query']),
    'getReportById' : IDL.Func([IDL.Nat], [RKHReport], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'queryRKHReports' : IDL.Func(
        [
          IDL.Record({
            'tahun' : IDL.Opt(IDL.Text),
            'tanggal' : IDL.Opt(IDL.Text),
            'user' : IDL.Opt(IDL.Principal),
            'bulan' : IDL.Opt(IDL.Text),
          }),
        ],
        [IDL.Vec(RKHReport)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'updateMyProfile' : IDL.Func([UserProfile], [], []),
    'updateReport' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'hasilKegiatan' : IDL.Text,
            'kegiatan' : IDL.Text,
            'tanggal' : IDL.Text,
            'lokasi' : IDL.Text,
            'keterangan' : IDL.Opt(IDL.Text),
            'jumlahSasaran' : IDL.Nat,
            'sasaran' : IDL.Text,
          }),
        ],
        [RKHReport],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };