/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RKHReport {
    id: bigint;
    hasilKegiatan: string;
    kegiatan: string;
    tanggal: string;
    createdAt: bigint;
    user: Principal;
    lokasi: string;
    keterangan?: string;
    jumlahSasaran: bigint;
    sasaran: string;
}
export interface UserProfile {
    nip: string;
    nama: string;
    wilayahKerja: string;
    nomorHp: string;
    jabatan: string;
    tandaTangan?: string;
    unitKerja: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addReport(report: RKHReport): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createRKHReport(input: {
        hasilKegiatan: string;
        kegiatan: string;
        tanggal: string;
        lokasi: string;
        keterangan?: string;
        jumlahSasaran: bigint;
        sasaran: string;
    }): Promise<RKHReport>;
    filterReportsByUser(user: Principal): Promise<Array<RKHReport>>;
    filterReportsByUserAndMonth(user: Principal, month: string): Promise<Array<RKHReport>>;
    filterReportsByUserAndMonthYear(user: Principal, month: string, year: string): Promise<Array<RKHReport>>;
    filterReportsByUserAndYear(user: Principal, year: string): Promise<Array<RKHReport>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getReportById(reportId: bigint): Promise<RKHReport>;
    getReports(): Promise<Array<RKHReport>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isValidNumaiIndicator(numaiIndicator: Array<bigint>): Promise<boolean>;
    queryReports(tanggal: string | null, bulan: string | null, tahun: string | null, user: Principal | null): Promise<Array<RKHReport>>;
    queryReportsYearly(filterYear: string): Promise<Array<RKHReport>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserRole(user: Principal, newRole: UserRole): Promise<void>;
    updateReport(reports: Array<RKHReport>): Promise<void>;
}
import type { RKHReport as _RKHReport, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addReport(arg0: RKHReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReport(to_candid_RKHReport_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReport(to_candid_RKHReport_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createRKHReport(arg0: {
        hasilKegiatan: string;
        kegiatan: string;
        tanggal: string;
        lokasi: string;
        keterangan?: string;
        jumlahSasaran: bigint;
        sasaran: string;
    }): Promise<RKHReport> {
        if (this.processError) {
            try {
                const result = await this.actor.createRKHReport(to_candid_record_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RKHReport_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRKHReport(to_candid_record_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RKHReport_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterReportsByUser(arg0: Principal): Promise<Array<RKHReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterReportsByUser(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterReportsByUser(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterReportsByUserAndMonth(arg0: Principal, arg1: string): Promise<Array<RKHReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterReportsByUserAndMonth(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterReportsByUserAndMonth(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterReportsByUserAndMonthYear(arg0: Principal, arg1: string, arg2: string): Promise<Array<RKHReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterReportsByUserAndMonthYear(arg0, arg1, arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterReportsByUserAndMonthYear(arg0, arg1, arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterReportsByUserAndYear(arg0: Principal, arg1: string): Promise<Array<RKHReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterReportsByUserAndYear(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterReportsByUserAndYear(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportById(arg0: bigint): Promise<RKHReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportById(arg0);
                return from_candid_RKHReport_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportById(arg0);
            return from_candid_RKHReport_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Array<RKHReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isValidNumaiIndicator(arg0: Array<bigint>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isValidNumaiIndicator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isValidNumaiIndicator(arg0);
            return result;
        }
    }
    async queryReports(arg0: string | null, arg1: string | null, arg2: string | null, arg3: Principal | null): Promise<Array<RKHReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryReports(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryReports(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryReportsYearly(arg0: string): Promise<Array<RKHReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryReportsYearly(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryReportsYearly(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateReport(arg0: Array<RKHReport>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReport(to_candid_vec_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReport(to_candid_vec_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_RKHReport_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RKHReport): RKHReport {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nip: string;
    nama: string;
    wilayahKerja: string;
    nomorHp: string;
    jabatan: string;
    tandaTangan: [] | [string];
    unitKerja: string;
}): {
    nip: string;
    nama: string;
    wilayahKerja: string;
    nomorHp: string;
    jabatan: string;
    tandaTangan?: string;
    unitKerja: string;
} {
    return {
        nip: value.nip,
        nama: value.nama,
        wilayahKerja: value.wilayahKerja,
        nomorHp: value.nomorHp,
        jabatan: value.jabatan,
        tandaTangan: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.tandaTangan)),
        unitKerja: value.unitKerja
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hasilKegiatan: string;
    kegiatan: string;
    tanggal: string;
    createdAt: bigint;
    user: Principal;
    lokasi: string;
    keterangan: [] | [string];
    jumlahSasaran: bigint;
    sasaran: string;
}): {
    id: bigint;
    hasilKegiatan: string;
    kegiatan: string;
    tanggal: string;
    createdAt: bigint;
    user: Principal;
    lokasi: string;
    keterangan?: string;
    jumlahSasaran: bigint;
    sasaran: string;
} {
    return {
        id: value.id,
        hasilKegiatan: value.hasilKegiatan,
        kegiatan: value.kegiatan,
        tanggal: value.tanggal,
        createdAt: value.createdAt,
        user: value.user,
        lokasi: value.lokasi,
        keterangan: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.keterangan)),
        jumlahSasaran: value.jumlahSasaran,
        sasaran: value.sasaran
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RKHReport>): Array<RKHReport> {
    return value.map((x)=>from_candid_RKHReport_n6(_uploadFile, _downloadFile, x));
}
function to_candid_RKHReport_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RKHReport): _RKHReport {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nip: string;
    nama: string;
    wilayahKerja: string;
    nomorHp: string;
    jabatan: string;
    tandaTangan?: string;
    unitKerja: string;
}): {
    nip: string;
    nama: string;
    wilayahKerja: string;
    nomorHp: string;
    jabatan: string;
    tandaTangan: [] | [string];
    unitKerja: string;
} {
    return {
        nip: value.nip,
        nama: value.nama,
        wilayahKerja: value.wilayahKerja,
        nomorHp: value.nomorHp,
        jabatan: value.jabatan,
        tandaTangan: value.tandaTangan ? candid_some(value.tandaTangan) : candid_none(),
        unitKerja: value.unitKerja
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hasilKegiatan: string;
    kegiatan: string;
    tanggal: string;
    createdAt: bigint;
    user: Principal;
    lokasi: string;
    keterangan?: string;
    jumlahSasaran: bigint;
    sasaran: string;
}): {
    id: bigint;
    hasilKegiatan: string;
    kegiatan: string;
    tanggal: string;
    createdAt: bigint;
    user: Principal;
    lokasi: string;
    keterangan: [] | [string];
    jumlahSasaran: bigint;
    sasaran: string;
} {
    return {
        id: value.id,
        hasilKegiatan: value.hasilKegiatan,
        kegiatan: value.kegiatan,
        tanggal: value.tanggal,
        createdAt: value.createdAt,
        user: value.user,
        lokasi: value.lokasi,
        keterangan: value.keterangan ? candid_some(value.keterangan) : candid_none(),
        jumlahSasaran: value.jumlahSasaran,
        sasaran: value.sasaran
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasilKegiatan: string;
    kegiatan: string;
    tanggal: string;
    lokasi: string;
    keterangan?: string;
    jumlahSasaran: bigint;
    sasaran: string;
}): {
    hasilKegiatan: string;
    kegiatan: string;
    tanggal: string;
    lokasi: string;
    keterangan: [] | [string];
    jumlahSasaran: bigint;
    sasaran: string;
} {
    return {
        hasilKegiatan: value.hasilKegiatan,
        kegiatan: value.kegiatan,
        tanggal: value.tanggal,
        lokasi: value.lokasi,
        keterangan: value.keterangan ? candid_some(value.keterangan) : candid_none(),
        jumlahSasaran: value.jumlahSasaran,
        sasaran: value.sasaran
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RKHReport>): Array<_RKHReport> {
    return value.map((x)=>to_candid_RKHReport_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
